baseurl = "https://jopplt.me"
title = "jopplt"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  showTitle = false
  author = "Josep Palet"
  info = "Software Engineer"
  description = "Welcome to my personal website!"
  keywords = "software,engineer,developer,josep,palet,jopplt,personal,website"
  gravatar = "jmpalet@gmail.com"

  colorScheme = "auto"
  hidecolorschemetoggle = false
  
# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/jopplt/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 4
  url = "https://linkedin.com/in/jopplt/"
